// Talent jobs - structured, data-driven representative open positions.
// This is showcase content: every job below is explicitly presented on
// the page as a REPRESENTATIVE OPEN POSITION, not a confirmed live
// Allsemi vacancy. No salary, company, office, job ID, or vacancy
// status is invented - "status" here only controls whether a record
// is shown/hidden on the public site, matching the field a future
// admin panel would actually use.
//
// Fields intentionally mirror what a future backend/admin system would
// need (id, slug, category, department, location, employmentType,
// experienceLevel, description blocks, skills, keywords, status,
// publishedAt/updatedAt, featured, applicationEnabled) so this file can
// be swapped for a real API response later without touching any page
// component.

export const JOB_CATEGORIES = [
  'Semiconductor', 'AI & Cloud', 'Automotive', 'Aerospace', 'Healthcare',
];

export const JOB_LOCATIONS = [
  'Bangalore, IN', 'Remote (India)', 'Hybrid',
];

export const JOBS = [
  {
    id: 'job-01',
    slug: 'rtl-design-engineer',
    title: 'RTL Design Engineer',
    category: 'Semiconductor',
    department: 'Chip Design',
    location: 'Bangalore, IN',
    employmentType: 'Full-time',
    experienceLevel: 'Mid-Senior',
    summary: 'RTL design for a digital ASIC/SoC programme, from micro-architecture through synthesis handoff.',
    description: 'This representative role sits inside a digital design team responsible for RTL implementation of a complex ASIC or SoC block, working from architectural specification through to a synthesis-ready netlist.',
    responsibilities: [
      'Author and maintain RTL in Verilog or SystemVerilog against a micro-architecture specification',
      'Work closely with verification to close functional coverage on owned blocks',
      'Support synthesis, timing closure, and CDC signoff for RTL handoff',
      'Participate in design and code reviews across the team',
    ],
    requiredSkills: ['Verilog', 'SystemVerilog', 'RTL Design', 'Digital Logic Design'],
    preferredSkills: ['Low Power Design', 'CDC', 'Synthesis Constraints'],
    keywords: ['RTL', 'Verilog', 'SystemVerilog', 'ASIC', 'SoC'],
    status: 'published',
    publishedAt: '2026-08-01',
    updatedAt: '2026-08-20',
    featured: true,
    applicationEnabled: true,
  },
  {
    id: 'job-02',
    slug: 'design-verification-engineer',
    title: 'Design Verification Engineer',
    category: 'Semiconductor',
    department: 'Verification',
    location: 'Bangalore, IN',
    employmentType: 'Full-time',
    experienceLevel: 'Mid-Senior',
    summary: 'UVM-based verification for block and SoC-level testbenches, driving functional coverage closure.',
    description: 'This representative role covers verification of digital design blocks and SoC-level integration, using a UVM methodology to build reusable, coverage-driven testbenches.',
    responsibilities: [
      'Develop and maintain UVM testbenches at block and SoC level',
      'Write test plans and drive functional coverage to closure',
      'Debug RTL and testbench issues in collaboration with design',
      'Contribute to verification methodology and reuse across projects',
    ],
    requiredSkills: ['SystemVerilog', 'UVM', 'Functional Coverage', 'Assertions'],
    preferredSkills: ['VCS', 'Xcelium', 'Questa', 'Formal Verification'],
    keywords: ['Verification', 'UVM', 'SystemVerilog', 'Coverage'],
    status: 'published',
    publishedAt: '2026-08-03',
    updatedAt: '2026-08-22',
    featured: true,
    applicationEnabled: true,
  },
  {
    id: 'job-03',
    slug: 'dft-engineer',
    title: 'DFT Engineer',
    category: 'Semiconductor',
    department: 'DFT',
    location: 'Bangalore, IN',
    employmentType: 'Full-time',
    experienceLevel: 'Mid-Senior',
    summary: 'Design-for-test insertion and ATPG pattern generation across a digital SoC design.',
    description: 'This representative role covers scan insertion, ATPG pattern generation, and DFT signoff for a digital SoC, working closely with physical design and verification teams.',
    responsibilities: [
      'Implement scan chain insertion and DFT architecture across the design',
      'Generate and validate ATPG patterns for stuck-at and transition fault coverage',
      'Support MBIST and boundary scan integration',
      'Work with physical design on DFT-related timing and routing constraints',
    ],
    requiredSkills: ['Scan Insertion', 'ATPG', 'DFT Architecture'],
    preferredSkills: ['MBIST', 'JTAG', 'Tessent', 'DFTMAX'],
    keywords: ['DFT', 'ATPG', 'Scan', 'MBIST'],
    status: 'published',
    publishedAt: '2026-07-28',
    updatedAt: '2026-08-15',
    featured: false,
    applicationEnabled: true,
  },
  {
    id: 'job-04',
    slug: 'physical-design-engineer',
    title: 'Physical Design Engineer',
    category: 'Semiconductor',
    department: 'Physical Design',
    location: 'Bangalore, IN',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    summary: 'Place-and-route and timing closure for a digital SoC block through to tape-out.',
    description: 'This representative role owns physical implementation of a digital block from floorplan through place-and-route to final timing and physical verification signoff.',
    responsibilities: [
      'Own floorplanning, placement, and clock tree synthesis for assigned blocks',
      'Drive static timing analysis and close setup/hold timing across corners',
      'Coordinate with DFT and verification on physical-aware constraints',
      'Support physical verification (DRC/LVS) signoff through tape-out',
    ],
    requiredSkills: ['Place and Route', 'STA', 'Timing Closure', 'Physical Implementation'],
    preferredSkills: ['Innovus', 'ICC2', 'PrimeTime', 'Low Power Physical Design'],
    keywords: ['Physical Design', 'PnR', 'STA', 'Tape-out'],
    status: 'published',
    publishedAt: '2026-07-20',
    updatedAt: '2026-08-10',
    featured: false,
    applicationEnabled: true,
  },
  {
    id: 'job-05',
    slug: 'embedded-software-engineer',
    title: 'Embedded Software Engineer',
    category: 'Automotive',
    department: 'Embedded Systems',
    location: 'Hybrid',
    employmentType: 'Full-time',
    experienceLevel: 'Mid-Senior',
    summary: 'Embedded C/C++ development for automotive-grade control and sensor systems.',
    description: 'This representative role covers embedded software development for automotive control systems, working within an AUTOSAR-adjacent environment on safety-relevant components.',
    responsibilities: [
      'Develop and maintain embedded C/C++ software for automotive control units',
      'Work within AUTOSAR or comparable automotive software architectures',
      'Support unit and integration testing against automotive quality standards',
      'Collaborate with systems and hardware teams on sensor and actuator interfaces',
    ],
    requiredSkills: ['Embedded C', 'C++', 'RTOS', 'Automotive Software'],
    preferredSkills: ['AUTOSAR', 'CAN/LIN', 'ISO 26262 Awareness'],
    keywords: ['Embedded', 'Automotive', 'C/C++', 'RTOS'],
    status: 'published',
    publishedAt: '2026-08-05',
    updatedAt: '2026-08-18',
    featured: false,
    applicationEnabled: true,
  },
  {
    id: 'job-06',
    slug: 'adas-engineer',
    title: 'ADAS Engineer',
    category: 'Automotive',
    department: 'ADAS',
    location: 'Hybrid',
    employmentType: 'Full-time',
    experienceLevel: 'Mid-Senior',
    summary: 'Sensor fusion and perception algorithm development for driver-assistance systems.',
    description: 'This representative role covers algorithm and systems development for ADAS features, spanning sensor fusion, perception, and integration with vehicle control systems.',
    responsibilities: [
      'Develop and tune sensor fusion algorithms across camera, radar, and lidar inputs',
      'Support perception pipeline development and validation',
      'Work with systems engineering on ADAS feature integration',
      'Contribute to validation test design for driver-assistance functions',
    ],
    requiredSkills: ['Sensor Fusion', 'C++', 'ADAS Systems'],
    preferredSkills: ['Python', 'ROS', 'Computer Vision'],
    keywords: ['ADAS', 'Sensor Fusion', 'Automotive', 'Perception'],
    status: 'published',
    publishedAt: '2026-08-08',
    updatedAt: '2026-08-24',
    featured: true,
    applicationEnabled: true,
  },
  {
    id: 'job-07',
    slug: 'functional-safety-engineer',
    title: 'Functional Safety Engineer',
    category: 'Automotive',
    department: 'Safety Engineering',
    location: 'Hybrid',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    summary: 'ISO 26262 functional safety process ownership for automotive electronic control systems.',
    description: 'This representative role owns functional safety analysis and process compliance for automotive electronic systems, working under ISO 26262 across the development lifecycle.',
    responsibilities: [
      'Lead hazard analysis and risk assessment (HARA) for assigned systems',
      'Own safety case documentation and ISO 26262 process compliance',
      'Work with design and verification teams on safety requirement traceability',
      'Support functional safety audits and assessments',
    ],
    requiredSkills: ['ISO 26262', 'Functional Safety', 'Hazard Analysis'],
    preferredSkills: ['ASIL Decomposition', 'FMEA', 'Safety Case Documentation'],
    keywords: ['Functional Safety', 'ISO 26262', 'Automotive'],
    status: 'published',
    publishedAt: '2026-07-25',
    updatedAt: '2026-08-12',
    featured: false,
    applicationEnabled: true,
  },
  {
    id: 'job-08',
    slug: 'rf-systems-engineer',
    title: 'RF Systems Engineer',
    category: 'Aerospace',
    department: 'RF Engineering',
    location: 'Bangalore, IN',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    summary: 'RF front-end and systems engineering for aerospace communications hardware.',
    description: 'This representative role covers RF systems engineering for aerospace and satellite communications hardware, from front-end design through system-level integration.',
    responsibilities: [
      'Design and analyze RF front-end circuits for communications hardware',
      'Support link budget analysis and system-level RF performance validation',
      'Work with embedded and systems teams on integration of RF subsystems',
      'Support qualification testing for high-reliability aerospace environments',
    ],
    requiredSkills: ['RF Design', 'Link Budget Analysis', 'Systems Engineering'],
    preferredSkills: ['Satellite Communications', 'Antenna Design', 'ADS/Microwave Office'],
    keywords: ['RF', 'Aerospace', 'Communications', 'Satellite'],
    status: 'published',
    publishedAt: '2026-07-15',
    updatedAt: '2026-08-05',
    featured: false,
    applicationEnabled: true,
  },
  {
    id: 'job-09',
    slug: 'cloud-platform-engineer',
    title: 'Cloud Platform Engineer',
    category: 'AI & Cloud',
    department: 'Infrastructure',
    location: 'Remote (India)',
    employmentType: 'Full-time',
    experienceLevel: 'Mid-Senior',
    summary: 'Distributed infrastructure engineering for large-scale AI compute platforms.',
    description: 'This representative role covers infrastructure engineering for large-scale AI compute platforms, spanning orchestration, scheduling, and platform reliability.',
    responsibilities: [
      'Build and operate distributed infrastructure for large-scale compute workloads',
      'Support GPU scheduling and resource orchestration at scale',
      'Own platform reliability, monitoring, and incident response',
      'Collaborate with ML engineering on infrastructure requirements',
    ],
    requiredSkills: ['Kubernetes', 'Distributed Systems', 'Cloud Infrastructure'],
    preferredSkills: ['GPU Scheduling', 'Terraform', 'Python or Go'],
    keywords: ['Cloud', 'Infrastructure', 'Kubernetes', 'AI Platform'],
    status: 'published',
    publishedAt: '2026-08-10',
    updatedAt: '2026-08-25',
    featured: true,
    applicationEnabled: true,
  },
  {
    id: 'job-10',
    slug: 'medical-device-engineer',
    title: 'Medical Device Engineer',
    category: 'Healthcare',
    department: 'Device Engineering',
    location: 'Bangalore, IN',
    employmentType: 'Full-time',
    experienceLevel: 'Mid-Senior',
    summary: 'Embedded and signal-processing engineering for diagnostic medical device hardware.',
    description: 'This representative role covers embedded and signal-processing engineering for diagnostic medical devices, operating within a regulated development process.',
    responsibilities: [
      'Develop embedded firmware and signal-processing algorithms for diagnostic hardware',
      'Support design controls and documentation under a regulated quality process',
      'Work with regulatory and quality teams on verification and validation activities',
      'Collaborate on hardware/firmware integration and test',
    ],
    requiredSkills: ['Embedded C', 'Signal Processing', 'Medical Device Development'],
    preferredSkills: ['ISO 13485', 'FDA 510(k) Awareness', 'DSP'],
    keywords: ['Healthcare', 'Medical Device', 'Embedded', 'Signal Processing'],
    status: 'published',
    publishedAt: '2026-07-30',
    updatedAt: '2026-08-19',
    featured: false,
    applicationEnabled: true,
  },
];

export function getPublishedJobs() {
  return JOBS.filter(j => j.status === 'published');
}

export function getJobBySlug(slug) {
  return JOBS.find(j => j.slug === slug && j.status === 'published');
}

export function getRelatedJobs(slug, count = 3) {
  const current = JOBS.find(j => j.slug === slug);
  if (!current) return [];
  return getPublishedJobs()
    .filter(j => j.slug !== slug)
    .sort((a, b) => (a.category === current.category ? -1 : 0) - (b.category === current.category ? -1 : 0))
    .slice(0, count);
}
